import { Arma } from "@/types/arma";

export const ARMAS: Arma[] = [
  {
    nome: "Espada",
    dano1m: "1d8",
    dano2m: "1d10",
    sangramento: 0,
    postura2m: 10,
    atributo: "Força",
  },
  {
    nome: "Espada Pesada",
    dano1m: "1d10",
    dano2m: "1d12",
    sangramento: 0,
    postura2m: 30,
    atributo: "Força",
  },
  {
    nome: "Maça",
    dano1m: "1d6",
    dano2m: "1d8",
    sangramento: 10,
    postura2m: 20,
    atributo: "Força",
  },
  {
    nome: "Lança",
    dano1m: "1d6",
    dano2m: "1d8",
    sangramento: 20,
    postura2m: 10,
    atributo: "Força",
  },
  {
    nome: "Machado",
    dano1m: "1d6",
    dano2m: "1d10",
    sangramento: 20,
    postura2m: 20,
    atributo: "Força",
  },
  {
    nome: "Uchigatana",
    dano1m: "1d8",
    dano2m: "1d10",
    sangramento: 10,
    postura2m: 10,
    atributo: "Destreza",
  },
  {
    nome: "Foice",
    dano1m: "1d10",
    dano2m: "1d12",
    sangramento: 20,
    postura2m: 30,
    atributo: "Destreza",
  },
  {
    nome: "Adaga",
    dano1m: "1d4",
    dano2m: "2d6",
    sangramento: 30,
    postura2m: 0,
    atributo: "Destreza",
  },
  {
    nome: "Lança",
    dano1m: "1d4",
    dano2m: "1d6",
    sangramento: 20,
    postura2m: 10,
    atributo: "Destreza",
  },
  {
    nome: "Arco",
    dano1m: "1",
    dano2m: "1d6",
    sangramento: 10,
    postura2m: 0,
    atributo: "Destreza",
  },
];
