import { FichaState } from "../types/state";

export const initialState: FichaState = {
  nomePersonagem: "",
  classe: "",
  nivel: 0,
  nomeJogador: "",
  atributos: {
    Força: 1,
    Destreza: 1,
    Constituição: 1,
    Inteligência: 1,
    Sabedoria: 1,
    Carisma: 1,
  },
  combate: {
    pontosVida: 0,
    defesaFisica: 0,
    defesaMagica: 0,
  },
  condicoes: [],
  venenos: [],
  traumas: [],
  aversoes: [],
  pericias: {
    Atletismo: { nivel: 0, marcas: 0 },
    Acrobacia: { nivel: 0, marcas: 0 },
    Furtividade: { nivel: 0, marcas: 0 },
    Prestidigitação: { nivel: 0, marcas: 0 },
    Percepção: { nivel: 0, marcas: 0 },
    Investigação: { nivel: 0, marcas: 0 },
    História: { nivel: 0, marcas: 0 },
    Arcanismo: { nivel: 0, marcas: 0 },
    Sobrevivência: { nivel: 0, marcas: 0 },
    Intuição: { nivel: 0, marcas: 0 },
    Enganação: { nivel: 0, marcas: 0 },
    Intimidação: { nivel: 0, marcas: 0 },
    Persuasão: { nivel: 0, marcas: 0 },
  },
  armas: [],
  magias: "",
  inventario: "",
  habilidades: "",
  historia: "",
  anotacoes: "",
};
